plugins {
    id 'com.android.application'
}

android {
    namespace 'com.cricos.app'
    compileSdk 35
    buildToolsVersion '33.0.2'

    defaultConfig {
        applicationId "com.cricos.app"
        minSdk 26
        targetSdk 35
        versionCode 2
        versionName "1.2.0"
    }

    signingConfigs {
        release {
            storeFile file('cricos-release.jks')
            storePassword 'cricos2026'
            keyAlias 'cricos_release'
            keyPassword 'cricos2026'
            enableV1Signing = true
            enableV2Signing = true
            enableV3Signing = true
            enableV4Signing = true
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            debuggable false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.release
            debuggable false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
